# build environment
FROM node:12.2.0-alpine as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json /app/package.json
RUN npm install --silent
RUN npm install react-scripts@3.0.1 -g --silent
COPY . /app
RUN npm run build

# production environment
FROM fholzer/nginx-brotli:v1.16.0
RUN rm -rf /var/cache/apk/* && rm -rf /tmp/*
COPY --from=build /app/build /usr/share/nginx/html

ADD nginx.conf /etc/nginx/
#ADD symfony.conf /etc/nginx/conf.d/
#ADD gzip.conf /etc/nginx/conf.d/
#ADD brotli.conf /etc/nginx/conf.d/