const BROKEN = "BROKEN";
const CREATE = "CREATE";
const CLOSED = "CLOSED";
const CONNECT = "CONNECT";
const DISCONNECT = "DISCONNECT";
const MESSAGE = "MESSAGE";
const OPEN = "OPEN";
const SEND = "SEND";

export const SET_USERNAME = "GENERAL::USERNAME";

export const LOBBYLIST_PREFIX = "LOBBYLIST";
export const CONNECT_LOBBYLIST = LOBBYLIST_PREFIX + "::" + CONNECT;
export const DISCONNECT_LOBBYLIST = LOBBYLIST_PREFIX + "::" + DISCONNECT;
export const MESSAGE_LOBBYLIST = LOBBYLIST_PREFIX + "::" + MESSAGE;
export const BROKEN_LOBBYLIST = LOBBYLIST_PREFIX + "::" + BROKEN;
export const CLOSED_LOBBYLIST = LOBBYLIST_PREFIX + "::" + CLOSED;
export const OPEN_LOBBYLIST = LOBBYLIST_PREFIX + "::" + OPEN;
export const SEND_LOBBYLIST = LOBBYLIST_PREFIX + "::" + SEND;

export const LOBBY_PREFIX = "LOBBY";
export const LOBBY_CREATE = LOBBY_PREFIX + "::" + CREATE;
export const LOBBY_MESSAGE = LOBBY_PREFIX + "::" + MESSAGE;
export const LOBBY_BROKEN = LOBBY_PREFIX + "::" + BROKEN;
export const LOBBY_OPEN = LOBBY_PREFIX + "::" + OPEN;
export const LOBBY_SEND = LOBBY_PREFIX + "::" + SEND;
export const LOBBY_DISCONNECT = LOBBY_PREFIX + "::" + DISCONNECT;
export const LOBBY_CLOSE = LOBBY_PREFIX + "::" + CLOSED;